   SCION-CP-PKI-TRC { 
       iso(1) identified-organization(3) dod(6) internet(1) security(5)
       mechanisms(5) pkix(7) id-mod(0) id-mod-scion-pki-trc(99) 
   }

   DEFINITIONS EXPLICIT TAGS ::= 
   BEGIN

    IMPORTS
      Certificate
       FROM PKIX1Explicit88 { 
           iso(1) identified-organization(3) dod(6) internet(1) 
          security(5) mechanisms(5) pkix(7) id-mod(0) id-pkix1-explicit(18) 
       };

    TRCValidity ::= SEQUENCE {
      notBefore      GeneralizedTime,
      notAfter       GeneralizedTime  }

   TRCPayload  ::=  SEQUENCE {
       version   TRCFormatVersion,
       iD        TRCID,
       validity  TRCValidity,

       gracePeriod   INTEGER,
       noTrustReset  BOOLEAN,
       votes         SEQUENCE SIZE (1..255) OF INTEGER,
       votingQuorum  INTEGER (1..255),
       coreASes           SEQUENCE OF ASN,
       authoritativeASes  SEQUENCE OF ASN,
       description        UTF8String (SIZE (0..1024)),
       certificates       SEQUENCE OF Certificate }

   TRCFormatVersion  ::=  INTEGER { v1(0) }

   TRCID  ::=  SEQUENCE {
       iSD           ISD,
       serialNumber  INTEGER (1..MAX),
       baseNumber    INTEGER (1..MAX) }

   ISD  ::=  INTEGER (1..65535)
   ASN  ::=  PrintableString

   END